stages:
  - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $(ls)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  #script:
  #  - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
  #  - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
  #  - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  #  - docker push $CI_REGISTRY_IMAGE
